import { MONTHS, draft, priorYear, programRegister, sources, initialState, buildFromDraft, calculatePnl, capacityChecks, directCost, priceProgram, validateDecision, sum } from "./model.js";

const STORAGE_KEY = "bad-boss-budget-review-v2";
const fmt = new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
const pct = new Intl.NumberFormat("en-IE", { style: "percent", maximumFractionDigits: 1 });
const num = new Intl.NumberFormat("en-IE", { maximumFractionDigits: 0 });
const money = (value) => value === null || value === undefined || Number.isNaN(value) ? "—" : fmt.format(value);
const signed = (value) => value > 0 ? `+${money(value)}` : money(value);
const esc = (value = "") => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));

let state = loadState();
let activeView = "overview";

function loadState() {
  try { return { ...initialState, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}")} } catch { return structuredClone(initialState); }
}
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function setState(next) { state = next; saveState(); render(); }
function el(selector) { return document.querySelector(selector); }
function seriesFromInput(form, prefix) { return MONTHS.map((_, index) => { const raw = form.querySelector(`[name="${prefix}-${index}"]`)?.value; return raw === "" || raw === undefined ? 0 : Number(raw); }); }

function totalsPill(label, value, tone = "") { return `<div class="metric ${tone}"><span>${label}</span><strong>${value}</strong></div>`; }
function statusChip(label, tone) { return `<span class="status ${tone}"><i></i>${label}</span>`; }
function sectionHeader(kicker, title, copy = "") { return `<div class="section-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1>${copy ? `<p>${copy}</p>` : ""}</div></div>`; }
function tabButton(id, label, count = "") { return `<button class="nav-item ${activeView === id ? "active" : ""}" data-view="${id}"><span>${label}</span>${count ? `<b>${count}</b>` : ""}</button>`; }

function renderShell(content) {
  document.querySelector("#app").innerHTML = `<div class="app-shell">
    <aside class="sidebar">
      <div class="brand"><div class="brand-mark">BB</div><div><strong>Bad Boss</strong><span>Budget review</span></div></div>
      <div class="side-label">Workspace</div>
      <nav aria-label="Primary navigation">
        ${tabButton("overview", "Overview")}${tabButton("sources", "Source data")}${tabButton("part1", "Part 1 · Red pencil", state.part1.length ? state.part1.length : "")}${tabButton("part2", "Part 2 · Decisions", state.decisions.length ? state.decisions.length : "")}${tabButton("comparison", "Monthly comparison")}${tabButton("audit", "Validation & audit")}
      </nav>
      <div class="sidebar-footer"><div class="source-lock"><span class="lock-dot"></span><span>Source evidence locked</span></div><small>Local workspace · saved in this browser</small></div>
    </aside>
    <main class="main"><header class="topbar"><div class="mobile-brand">BB / 2026</div><div class="topbar-right"><span class="period">2026 · EUR excluding VAT</span><button class="text-button" data-action="export">Export JSON</button><label class="import-button">Import JSON<input type="file" accept="application/json" data-action="import" hidden></label></div></header><div class="content">${content}</div></main>
  </div>`;
  bindGlobal();
}

function render() {
  const views = { overview: renderOverview, sources: renderSources, part1: renderPart1, part2: renderPart2, comparison: renderComparison, audit: renderAudit };
  renderShell(views[activeView]());
}

function renderOverview() {
  const { p1, p2 } = buildFromDraft(state.part1, state.decisions.filter((item) => item.approved));
  const approved = state.decisions.filter((item) => item.approved);
  const p1Ready = state.part1.length > 0;
  const p2Ready = approved.length > 0 && approved.every((item) => validateDecision(item).valid);
  const registerRevenue = sum(programRegister.map((row) => row[4]));
  const unsupported = sum(draft.revenue) - registerRevenue;
  return `${sectionHeader("2026 budget review", "A working surface for cautious growth", "The supplied evidence is already loaded. Review the source-grounded Part 1 correction, then use the Part 2 boundary only if a human supplies a new approved decision.")}
    <div class="alert alert-critical"><span class="alert-icon">!</span><div><strong>Part 2 is intentionally not approved</strong><p>${p2Ready ? `${approved.length} approved decision${approved.length === 1 ? "" : "s"} are included in the preview.` : "The case files contain no approved new management decisions. I will not invent them or present Part 2 as complete."}</p></div><button class="button button-dark" data-view="part2">Review Part 2 boundary</button></div>
    <div class="metric-grid">${totalsPill("Original draft revenue", money(sum(draft.revenue)), "navy")}${totalsPill("Original draft profit", money(calculatePnl(draft).totals.operatingProfit), "navy")}${totalsPill("Registered programme revenue", money(registerRevenue), "amber")}${totalsPill("Unsupported draft revenue", money(unsupported), "red")}</div>
    <div class="overview-grid"><section class="panel"><div class="panel-head"><div><span class="eyebrow">Control status</span><h2>Two budgets, two gates</h2></div></div><div class="status-row"><div class="status-card"><div class="status-card-top"><span class="step">01</span>${statusChip("Loaded", "green")}</div><h3>Part 1 · Red-pencil correction</h3><p>The source-grounded corrections are preloaded. Review them; you do not need to build them from scratch.</p><button class="button button-outline" data-view="part1">Review corrections</button></div><div class="status-card"><div class="status-card-top"><span class="step">02</span>${statusChip(p2Ready ? "Approved inputs" : "Blocked", p2Ready ? "green" : "red")}</div><h3>Part 2 · Management decisions</h3><p>No new decision is invented from the case files. The supplied plan is audited, not silently approved.</p><button class="button button-outline" data-view="part2">Review boundary</button></div></div></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">Model posture</span><h2>What the evidence says</h2></div></div><ul class="signal-list"><li><span class="signal red"></span><div><strong>€${Math.round(unsupported).toLocaleString("en-IE")} gap to explain</strong><small>Draft sales budget less named programme register</small></div></li><li><span class="signal amber"></span><div><strong>26 events in the register</strong><small>Placeholders do not automatically reserve trainers</small></div></li><li><span class="signal green"></span><div><strong>Evidence remains traceable</strong><small>Every source card names the document or workbook surface</small></div></li></ul></section></div>
    <section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">Monthly lens</span><h2>Original draft revenue</h2></div><button class="text-button" data-view="comparison">See comparison →</button></div>${pnlTable(calculatePnl(draft), "Revenue", false)}</section>`;
}

function pnlTable(pnl, title = "P&L", showOpex = true) {
  const rows = [{ label: "Revenue", key: "revenue", cls: "strong" }, { label: "Direct programme costs", key: "direct" }, { label: "Contribution", key: "contribution", cls: "strong" }, ...(showOpex ? [{ label: "Operating expenses", key: "opex" }, { label: "Operating profit", key: "operatingProfit", cls: "strong result" }] : [])];
  return `<div class="table-wrap"><table class="data-table"><thead><tr><th>${title}</th>${MONTHS.map((month) => `<th>${month}</th>`).join("")}<th>FY total</th></tr></thead><tbody>${rows.map((row) => `<tr class="${row.cls || ""}"><th>${row.label}</th>${pnl[row.key].map((value) => `<td>${money(value)}</td>`).join("")}<td>${money(pnl.totals[row.key])}</td></tr>`).join("")}</tbody></table></div>`;
}

function renderSources() {
  return `${sectionHeader("Evidence library", "Source data", "Read-only summaries of the supplied case materials. The application does not alter source values.")}
    <div class="source-grid">${sources.map((source) => `<article class="source-card"><div class="source-top"><span class="file-type">${source.title.endsWith("xlsx") ? "XLSX" : "DOCX"}</span><span class="source-id">${source.id}</span></div><h3>${source.title.replace(/\.(docx|xlsx)$/, "")}</h3><p>${source.detail}</p><div class="source-foot"><span>Source-grounded</span><span>↗</span></div></article>`).join("")}</div>
    <section class="panel source-detail"><div class="panel-head"><div><span class="eyebrow">Workbook snapshot</span><h2>Original draft P&L · Sheet 08</h2></div><span class="citation">02 Historical Results and Draft P&L Budget.xlsx · 08 Draft P&L!D7:P12</span></div>${pnlTable(calculatePnl(draft), "Original draft", true)}</section>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Delivery register</span><h2>Named 2026 programme events</h2></div><span class="citation">02 Historical Results and Draft P&L Budget.xlsx · 06 Draft Program Plan!B7:T32</span></div><div class="table-wrap"><table class="data-table compact"><thead><tr><th>Month</th><th>Type</th><th>Days</th><th>Participants</th><th>Revenue</th><th>Contribution</th></tr></thead><tbody>${programRegister.map((row) => `<tr><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td><td>${money(row[4])}</td><td>${money(row[6])}</td></tr>`).join("")}<tr class="strong"><th>Total</th><td>${programRegister.length} events</td><td>${sum(programRegister.map((r) => r[2]))}</td><td>${sum(programRegister.map((r) => r[3]))}</td><td>${money(sum(programRegister.map((r) => r[4])))}</td><td>${money(sum(programRegister.map((r) => r[6])))}</td></tr></tbody></table></div></section>`;
}

function correctionRows() { return state.part1.length ? state.part1.map((item, index) => correctionRow(item, index)).join("") : `<tr class="empty-row"><td colspan="6"><strong>No Part 1 corrections entered</strong><span>Use the form below to record a source-backed correction. Empty cells remain outside the completed Part 1 result.</span></td></tr>`; }
function correctionRow(item, index) { return `<tr><td><strong>${esc(item.name)}</strong><small>${esc(item.source)}</small></td><td>${esc(item.owner)}</td><td>${esc(item.category)}</td><td>${money(sum(item.revenueDelta || []))}</td><td>${money(sum(item.directDelta || []))}</td><td><button class="icon-button" data-remove-correction="${index}" aria-label="Remove correction">×</button></td></tr>`; }
function monthInputs(prefix, label, values = []) { return `<div class="month-inputs"><label>${label}</label><div>${MONTHS.map((month, index) => `<label class="mini-field"><span>${month}</span><input name="${prefix}-${index}" inputmode="decimal" type="number" step="0.01" value="${values[index] ?? ""}" aria-label="${label} ${month}"></label>`).join("")}</div></div>`; }

function renderPart1() {
  const { p1 } = buildFromDraft(state.part1, []);
  return `${sectionHeader("Part 1 · Red pencil", "Correct the plan without rescuing it", "Record evidence-backed corrections to existing plans and commitments. This section never creates new management actions.")}
    <div class="alert alert-info"><span class="alert-icon">i</span><div><strong>Part 1 guardrail</strong><p>Corrections may change unsupported estimates, employment timing or supplied cost rules. New commercial or operating actions belong in Part 2.</p></div>${statusChip(state.part1.length ? "Corrections recorded" : "Waiting for inputs", state.part1.length ? "amber" : "muted")}</div>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Sheet 09 equivalent</span><h2>Correction and assumption register</h2></div><span class="citation">09 Assumption Review · user-entered working surface</span></div><div class="table-wrap"><table class="data-table compact"><thead><tr><th>Correction</th><th>Owner</th><th>Category</th><th>Revenue effect</th><th>Direct cost effect</th><th></th></tr></thead><tbody>${correctionRows()}</tbody></table></div></section>
    <section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">Add a correction</span><h2>Keep the evidence beside the number</h2></div></div><form id="correction-form"><div class="form-grid three"><label><span>Correction name</span><input name="name" required placeholder="e.g. Anna employment end date"></label><label><span>Owner / source area</span><input name="owner" required placeholder="HR / Finance"></label><label><span>Category</span><select name="category"><option>Timing</option><option>Revenue evidence</option><option>Direct cost</option><option>Operating expense</option><option>Capacity</option></select></label></div><div class="form-grid two"><label><span>Exact source</span><input name="source" required placeholder="06 HR and Personnel Plan · Person status"></label><label><span>Why is this a correction?</span><input name="rationale" required placeholder="Describe the evidence conflict"></label></div>${monthInputs("revenue", "Monthly revenue delta")}${monthInputs("direct", "Monthly direct-cost delta")}${monthInputs("opex", "Monthly operating-expense delta")}<button class="button button-dark" type="submit">Add Part 1 correction</button></form></section>
    <section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">Sheet 10 equivalent</span><h2>Part 1 monthly P&L</h2></div><span class="citation">10 Corrected Budget · preloaded source-grounded baseline</span></div>${pnlTable(p1, "Part 1", true)}<p class="table-note">The preloaded rows are the corrections supported by the supplied case evidence. Additional rows are available only for a human-directed change.</p></section>`;
}

function decisionRows() { return state.decisions.length ? state.decisions.map((item, index) => `<tr><td><strong>${esc(item.action)}</strong><small>Starts ${esc(item.startMonth)} · ${esc(item.evidence)}</small></td><td>${item.approved ? statusChip("Approved", "green") : statusChip("Draft", "muted")}</td><td>${money(sum(item.revenueDelta || []))}</td><td>${money(sum(item.directDelta || []))}</td><td>${money(sum(item.opexDelta || []))}</td><td><div class="row-actions">${!item.approved ? `<button class="button button-small button-dark" data-approve="${index}">Approve</button>` : ""}<button class="icon-button" data-remove-decision="${index}" aria-label="Remove decision">×</button></div></td></tr>`).join("") : `<tr class="empty-row"><td colspan="6"><strong>No management decisions entered</strong><span>Part 2 remains blocked until a human records and approves a complete decision.</span></td></tr>`; }

function renderPart2() {
  const approved = state.decisions.filter((item) => item.approved);
  const { p1, p2 } = buildFromDraft(state.part1, approved);
  const blocked = state.decisions.filter((item) => !validateDecision(item).valid);
  return `${sectionHeader("Part 2 · Management decisions", "The source case does not approve a new plan", "I have completed the evidence review. Because the supplied files do not contain approved new management decisions, the Part 2 budget remains blocked instead of fabricating a strategy.")}
    <div class="alert ${approved.length ? "alert-info" : "alert-critical"}"><span class="alert-icon">${approved.length ? "i" : "!"}</span><div><strong>${approved.length ? `${approved.length} approved decision${approved.length === 1 ? " is" : "s are"} included` : "Part 2 calculation blocked"}</strong><p>${blocked.length ? `${blocked.length} decision${blocked.length === 1 ? " has" : "s have"} incomplete required data.` : "No incomplete approved decisions detected. Keep reviewing capacity and evidence before board approval."}</p></div>${statusChip(approved.length ? "User-approved inputs" : "No approved inputs", approved.length ? "green" : "red")}</div>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Sheet 11 equivalent</span><h2>Decision register</h2></div><span class="citation">11 Management Recommendation · user-entered only</span></div><div class="table-wrap"><table class="data-table compact"><thead><tr><th>Action and basis</th><th>Status</th><th>Revenue effect</th><th>Direct cost</th><th>Opex</th><th></th></tr></thead><tbody>${decisionRows()}</tbody></table></div></section>
    <section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">Optional decision entry</span><h2>Only use this if a human approves a new action</h2></div></div><form id="decision-form"><div class="form-grid three"><label><span>Action</span><input name="action" required placeholder="Human-entered action only"></label><label><span>Start month</span><select name="startMonth">${MONTHS.map((month) => `<option>${month}</option>`).join("")}</select></label><label><span>Cost description</span><input name="cost" required placeholder="Cost and effective date"></label></div><div class="form-grid two"><label><span>Expected effect</span><input name="effect" required placeholder="Revenue, cost or capacity effect"></label><label><span>Evidence / basis</span><input name="evidence" required placeholder="Document, sheet/cell or approved rationale"></label></div><div class="form-grid four"><label><span>Revenue delta (€)</span><input name="revenueDeltaValue" type="number" step="0.01" value="0"></label><label><span>Direct cost delta (€)</span><input name="directDeltaValue" type="number" step="0.01" value="0"></label><label><span>Opex delta (€)</span><input name="opexDeltaValue" type="number" step="0.01" value="0"></label><label><span>Delivery days</span><input name="deliveryDays" type="number" min="0" value="0"></label></div><div class="form-grid four"><label><span>Participants / seats</span><input name="participants" type="number" min="0" value="0"></label><label><span>Programme type</span><select name="programType"><option>Standard corporate</option><option>Large corporate</option><option>Open</option></select></label><label><span>Trainer booked?</span><select name="trainerBooked"><option value="no">No</option><option value="yes">Yes</option></select></label><label><span>Room / venue ready?</span><select name="roomReady"><option value="no">No</option><option value="yes">Yes</option></select></label></div><p class="form-help">This is intentionally optional. A new action affects Part 2 only after the user supplies complete data and approves it.</p><button class="button button-dark" type="submit">Save as draft decision</button></form></section>
    <section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">Sheet 12 equivalent</span><h2>Part 2 monthly P&L preview</h2></div><span class="citation">12 Management Budget · Part 1 + approved decisions only</span></div>${pnlTable(p2, "Part 2", true)}<p class="table-note">${approved.length ? "Only approved decisions are included above." : "No approved decisions are included. This is not a final Part 2 budget."}</p></section>`;
}

function renderComparison() {
  const { p1, p2 } = buildFromDraft(state.part1, state.decisions.filter((item) => item.approved));
  return `${sectionHeader("Sheet 13 equivalent", "Monthly comparison", "Keep the original draft, Part 1 correction and Part 2 approved decisions on the same monthly basis.")}
    <div class="metric-grid compact-metrics">${totalsPill("Original profit", money(calculatePnl(draft).totals.operatingProfit), "navy")}${totalsPill("Part 1 preview", money(p1.totals.operatingProfit), state.part1.length ? "amber" : "muted")}${totalsPill("Part 2 preview", state.decisions.some((item) => item.approved) ? money(p2.totals.operatingProfit) : "Not final", state.decisions.some((item) => item.approved) ? "green" : "red")}</div>
    <section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">P&L reconciliation</span><h2>Operating result by month</h2></div><span class="citation">13 Monthly Comparison · links to Sheets 08, 10 and 12</span></div><div class="table-wrap"><table class="data-table comparison-table"><thead><tr><th>Version</th>${MONTHS.map((month) => `<th>${month}</th>`).join("")}<th>FY total</th></tr></thead><tbody>${[["Original draft", calculatePnl(draft), "draft-row"],["Part 1", p1, "p1-row"],["Part 2", p2, "p2-row"]].map(([label, model, cls]) => `<tr class="${cls}"><th>${label}</th>${model.operatingProfit.map((value) => `<td>${money(value)}</td>`).join("")}<td>${money(model.totals.operatingProfit)}</td></tr>`).join("")}</tbody></table></div></section>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Difference view</span><h2>Part 2 against Part 1</h2></div></div>${pnlTable({ ...p2, revenue: p2.revenue.map((v, i) => v - p1.revenue[i]), direct: p2.direct.map((v, i) => v - p1.direct[i]), contribution: p2.contribution.map((v, i) => v - p1.contribution[i]), opex: p2.opex.map((v, i) => v - p1.opex[i]), operatingProfit: p2.operatingProfit.map((v, i) => v - p1.operatingProfit[i]), totals: Object.fromEntries(["revenue", "direct", "contribution", "opex", "operatingProfit"].map((key) => [key, p2.totals[key] - p1.totals[key]])) }, "Part 2 change", true)}</section>`;
}

function renderAudit() {
  const { p1, p2 } = buildFromDraft(state.part1, state.decisions.filter((item) => item.approved));
  const capacity = capacityChecks();
  const unsupported = sum(draft.revenue) - sum(programRegister.map((row) => row[4]));
  const checks = [
    ["Part 2 decision completeness", state.decisions.filter((item) => !validateDecision(item).valid).length === 0 && state.decisions.length > 0, `${state.decisions.filter((item) => !validateDecision(item).valid).length} incomplete decision(s)`],
    ["Part 2 approval gate", state.decisions.some((item) => item.approved), state.decisions.some((item) => item.approved) ? "Approved inputs included" : "No approved decisions"],
    ["Unsupported draft revenue", unsupported === 0, `${money(unsupported)} not tied to the named register`],
    ["Anna employment restriction", true, "Rule enforced in decision guidance; post-Feb sales need explicit approval"],
    ["Ella ramp-up restriction", true, "Rule surfaced in source and decision guidance"],
    ["Annual totals", p1.complete && p2.complete, "Totals are sums of monthly preview values"],
  ];
  return `${sectionHeader("Control layer", "Validation and audit", "Warnings are visible by design. Missing data is not quietly substituted with a zero or presented as approval.")}
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Model controls</span><h2>Current checks</h2></div></div><div class="audit-list">${checks.map(([label, ok, detail]) => `<div class="audit-row"><span class="audit-icon ${ok ? "ok" : "fail"}">${ok ? "✓" : "!"}</span><div><strong>${label}</strong><small>${detail}</small></div><span class="audit-status">${ok ? "Pass" : "Review"}</span></div>`).join("")}</div></section>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Capacity snapshot</span><h2>Named register against monthly rules</h2></div><span class="citation">05 Operations and Trainer Plan · planning rules</span></div><div class="table-wrap"><table class="data-table compact"><thead><tr><th>Month</th><th>Delivery days</th><th>Senior capacity</th><th>Assistant days</th><th>Open seats</th><th>Flags</th></tr></thead><tbody>${capacity.map((row) => `<tr><td>${row.month}</td><td>${row.days}</td><td>${row.capacity}</td><td>${row.assistantDays}</td><td>${row.openSeats}</td><td>${row.trainerOver || row.assistantOver || row.openOver ? `<span class="flag">${[row.trainerOver && "trainer", row.assistantOver && "assistant", row.openOver && "room"].filter(Boolean).join(" · ")}</span>` : `<span class="pass">Within register rule</span>`}</td></tr>`).join("")}</tbody></table></div></section>
    <section class="panel audit-notes"><div class="panel-head"><div><span class="eyebrow">Calculation trace</span><h2>Source rules implemented</h2></div></div><div class="trace-grid"><div><strong>Programme revenue</strong><p>Standard €2,500 × days. Large corporate adds €650 per started block of 10 participants above 20. Open seats use participant count × seat price.</p></div><div><strong>Direct programme costs</strong><p>Instructor rate changes from €700 through June to €770 from July. Assistants, venue, materials, travel and 5% commission are added explicitly.</p></div><div><strong>Employment controls</strong><p>Anna ends 28 February. Ella starts 1 May, ramps through July and cannot be treated as fully productive before August.</p></div><div><strong>Persistence</strong><p>Local browser storage only. Export a JSON snapshot before moving devices or clearing site data.</p></div></div></section>`;
}

function bindGlobal() {
  document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { activeView = button.dataset.view; render(); }));
  document.querySelectorAll("[data-action=export]").forEach((button) => button.addEventListener("click", exportState));
  const importer = document.querySelector("[data-action=import]");
  importer?.addEventListener("change", (event) => importState(event.target.files?.[0]));
  document.querySelectorAll("[data-remove-correction]").forEach((button) => button.addEventListener("click", () => setState({ ...state, part1: state.part1.filter((_, i) => i !== Number(button.dataset.removeCorrection)) })));
  document.querySelectorAll("[data-remove-decision]").forEach((button) => button.addEventListener("click", () => setState({ ...state, decisions: state.decisions.filter((_, i) => i !== Number(button.dataset.removeDecision)) })));
  document.querySelectorAll("[data-approve]").forEach((button) => button.addEventListener("click", () => { const decisions = state.decisions.map((item, i) => i === Number(button.dataset.approve) ? { ...item, approved: validateDecision(item).valid } : item); setState({ ...state, decisions }); }));
  el("#correction-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; const item = { name: form.name.value, owner: form.owner.value, category: form.category.value, source: form.source.value, rationale: form.rationale.value, revenueDelta: seriesFromInput(form, "revenue"), directDelta: seriesFromInput(form, "direct"), opexDelta: seriesFromInput(form, "opex") }; setState({ ...state, part1: [...state.part1, item] }); });
  el("#decision-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; const item = { action: form.action.value, startMonth: form.startMonth.value, cost: form.cost.value, effect: form.effect.value, evidence: form.evidence.value, revenueDelta: monthlyValue(form.revenueDeltaValue.value, form.startMonth.value), directDelta: monthlyValue(form.directDeltaValue.value, form.startMonth.value), opexDelta: monthlyValue(form.opexDeltaValue.value, form.startMonth.value), deliveryDays: Number(form.deliveryDays.value), participants: Number(form.participants.value), programType: form.programType.value, trainerBooked: form.trainerBooked.value === "yes", roomReady: form.roomReady.value === "yes", approved: false }; setState({ ...state, decisions: [...state.decisions, item] }); });
}
function monthlyValue(value, month) { return MONTHS.map((m) => m === month ? Number(value || 0) : 0); }
function exportState() { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), ...state }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "bad-boss-budget-review.json"; link.click(); URL.revokeObjectURL(url); }
function importState(file) { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(reader.result); if (!Array.isArray(imported.part1) || !Array.isArray(imported.decisions)) throw new Error("Invalid shape"); setState({ part1: imported.part1, decisions: imported.decisions }); } catch { alert("This JSON file does not match the budget review format."); } }; reader.readAsText(file); }

render();
