import assert from "node:assert/strict";
import { MONTHS, initialState, strategyDecisions, buildFromDraft, priceProgram, directCost, capacityChecks, validateDecision } from "./model.js";

assert.equal(strategyDecisions.length, 5);
assert.deepEqual(MONTHS, ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]);
assert.equal(priceProgram("Standard corporate", 2, 20), 5000);
assert.equal(priceProgram("Large corporate", 2, 21), 6300);
assert.equal(priceProgram("Large corporate", 2, 60), 10200);
assert.equal(priceProgram("Open", 2, 20, 300), 6000);
assert.equal(directCost({ type: "Standard corporate", days: 1, participants: 20, month: "Jun" }).instructor, 700);
assert.equal(directCost({ type: "Standard corporate", days: 1, participants: 20, month: "Jul" }).instructor, 770);
assert.equal(capacityChecks().length, 12);
const { p1, p2 } = buildFromDraft(initialState.part1, strategyDecisions);
assert.equal(p1.revenue[2], 15000);
assert.equal(p1.revenue[5], 12750);
assert.equal(p1.revenue[8], 17000);
assert.equal(p1.revenue[10], 16800);
assert.equal(p1.totals.revenue, 146650);
assert.equal(p2.revenue[5], 22750);
assert.equal(p2.totals.revenue, 216650);
assert.equal(validateDecision(strategyDecisions[0]).valid, true);
console.log("Domain tests passed.");
