import assert from "node:assert/strict";
import { directCost, priceProgram, capacityChecks, validateDecision, MONTHS } from "../src/model.js";
assert.equal(priceProgram("Standard corporate", 2, 20), 5000);
assert.equal(priceProgram("Large corporate", 1, 20), 2500);
assert.equal(priceProgram("Large corporate", 1, 21), 3150);
assert.equal(priceProgram("Large corporate", 1, 30), 3150);
assert.equal(priceProgram("Large corporate", 1, 31), 3800);
assert.equal(priceProgram("Large corporate", 1, 60), 5100);
assert.equal(priceProgram("Large corporate", 1, 61), 5750);
assert.equal(priceProgram("Large corporate", 1, 90), 7050);
assert.equal(priceProgram("Large corporate", 1, 100), 7700);
assert.equal(directCost({ type: "Standard corporate", days: 1, participants: 20, month: "Jun" }).instructor, 700);
assert.equal(directCost({ type: "Standard corporate", days: 1, participants: 20, month: "Jul" }).instructor, 770);
assert.equal(directCost({ type: "Large corporate", days: 2, participants: 60, month: "Jun" }).assistants, 350);
assert.equal(directCost({ type: "Open", days: 1, participants: 20, month: "Jan", seatPrice: 500 }).venue, 600);
assert.equal(capacityChecks().length, MONTHS.length);
assert.equal(validateDecision({ action: "x" }).valid, false);
assert.equal(validateDecision({ action: "x", startMonth: "Jan", cost: "0", effect: "0", evidence: "source", revenueDelta: [], directDelta: [], opexDelta: [] }).valid, true);
console.log("Domain tests passed.");
